version: 2.1

jobs:
  build:
    working_directory: ~/kumite
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: >-
            mkdir ~/.aws &&
            echo -e "[kumite-recorder]\naws_access_key_id=$AWS_ACCESS_KEY_ID_PROD\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_PROD\n" > ~/.aws/credentials &&
            cd ./IAC && wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip && unzip terraform_0.12.3_linux_amd64.zip
      - run:
          name: Initialize terraform
          command: cd ./IAC && ./terraform init
      - run:
          name: Deploy infrastructure
          command: cd ./IAC && ./terraform apply --auto-approve