version: 2.1

jobs:
  build:
    working_directory: ~/kumite/IAC

    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Prepare environment
          command: wget https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip && unzip terraform_0.12.3_linux_amd64.zip
      - run:
          name: Initialize terraform
          command: ./terraform init
      - run:
          name: Deploy infrastructure
          command: ./terraform apply --auto-approve